name: Run Titanic R Scripts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr","ggplot2"))'

      - name: Run all scripts
        run: |
          Rscript scripts/01_data_cleaning.R
          Rscript scripts/02_demographic_analysis.R
          Rscript scripts/03_survival_analysis.R
          Rscript scripts/04_visualization.R
